### ISSUE TITLE
Problema no site receitinhas.com.br

### ISSUE THREAD

**Issue by kassya** [kassya/2048-python#3]
Há defeito na publicação abaixo do site receitinhas.com.br

https://receitinhas.com.br/web-stories/bolinho-de-chuva/

Conseguem me ajudar, relatando o(s) defeitos(s) ?

Muito obrigada

Kassya

**Comment by jeffersoncdantas** [comment]
No começo ele fala que está fazendo uma receita de bolinho de chuva, e na hora do preparo ele fala sobre tirinhas de frango

**Comment by GPauleti** [comment]
Passo 2 - Contém a foto e descrição para bolinhos de chuva mas o passo descreve uma receita para tiras de frango

**Comment by Felipe-Garbi** [comment]
Todos os passos são iguais

**Comment by LittleLion2** [comment]
Os passo a passo possuem o mesmo texto

**Comment by felipih** [comment]
Não sou especialista, porém no bolinho de chuva não vai páprica nem frango... no passo 1 fala que usa ambos

**Comment by DaniAloia** [comment]
O Passo 1, 2 e 3 está com o texto repetido e o texto fala sobre tiras de frango e não sobre o bolinho de chuva.

**Comment by leonear** [comment]
Na terceira página não há nenhuma descrição sobre a receita, fora a formatação do tempo e ingredientes.

**Comment by Naomi0806** [comment]
No passo 2 esta descrito uma receita de tiras de frango sendo que a receita é de um bolinho de chuva

**Comment by CaueLonghi** [comment]
-Os textos das descrições dos passos são iguais

**Comment by RoddGarcia** [comment]
Os 3 primeiros passos são iguais

**Comment by GustavoPivatto** [comment]
A receita fala sobre bolinhos de chuvas, mas no passo a passo fala de uma receita que utiliza frango e páprica (algo que não é usado normalmente na receita), além das descrições dos passos serem iguais.

**Comment by sanchesprogramer** [comment]
A receita se trata de um bolinho de chuva, porém no passo a passo a receita se tornou outra

**Comment by pedrohwbarbosa** [comment]
O passo 1, 2 e 3 possuem o mesmo texto. Ademais, a receita deveria ser sobre bolinho de chuva entretanto tratasse de como fazer tiras de frango

**Comment by citricgio** [comment]
Existe um traço no segundo slide no texto "40 minutos"

**Comment by felipih** [comment]
> A receita se trata de um bolinho de chuva, porém no passo a passo a receita se tornou antes

Sabe escrever Mooca?

**Comment by 2huyu** [comment]
Todos os passos são iguais e os stories iniciam pelo final

**Comment by EduardoFelizardo** [comment]
Os passos 1, 2 e 3 estão com o mesmo texto, além de que o modo de preparo não condiz com os ingredientes listados e com a proposta final que seria bolinhos de chuva

**Comment by FernandesNz** [comment]
Todos os passos são iguais, sendo mencionado uma receita de tiras de frango.
